# Generated by Django 5.2.1 on 2025-09-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=100)),
                ('end_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.route')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ALL', 'All'), ('LADIES', 'Ladies'), ('SENIOR', 'Senior Citizen')], default='ALL', max_length=20)),
                ('seats_booked', models.IntegerField()),
                ('confirmed_seats', models.IntegerField(default=0)),
                ('waitlist_seats', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist')], default='CONFIRMED', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.train')),
            ],
        ),
    ]
