# Generated by Django 5.2.1 on 2025-09-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_city',
            new_name='endcity',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_city',
            new_name='startcity',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='booked_at',
            new_name='bookedat',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='confirmed_seats',
            new_name='confirmedseats',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='passenger_name',
            new_name='passengername',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='seats_booked',
            new_name='seatsbooked',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='waitlist_seats',
            new_name='waitlistseats',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='available_seats',
            new_name='availableseats',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='total_seats',
            new_name='totalseats',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='train_name',
            new_name='trainname',
        ),
    ]
