# Generated by Django 5.2.1 on 2025-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_end_city_route_endcity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='waiting_list_capacity',
            field=models.IntegerField(default=10),
        ),
    ]
